# Generated by Django 6.0.5 on 2026-05-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cvc', models.CharField(max_length=4)),
                ('is_default', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'payment_methods',
                'managed': False,
            },
        ),
    ]
