# Generated by Django 6.0.5 on 2026-05-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paymentmethods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cartitems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coupons',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phonenumbers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategories',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productvariants',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wishlists',
            options={},
        ),
    ]
